services:
  - type: web
    name: taskmanager-client
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/TaskManagerClient/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html